fix(r/burn_alert): handle existing remote description with default description value (#575)
When upgrading to 0.28.0, if you have an existing burn alert that had a
description set (via the UI, most likely) but the description was yet to
be added to HCL config you will get the following error:

```
Error: Provider produced inconsistent result after apply
        
        When applying changes to honeycombio_burn_alert.test, provider
        "provider[\"registry.terraform.io/hashicorp/honeycombio\"]" produced an
        unexpected new value: .description: was cty.StringVal(""), but now
        cty.StringVal("test description").
```

Fix is to ensure we send the empty string when we marshal our JSON