fix(r/query_annotation): handle empty description (#747)
Fixes the follow error if `description` was empty:

> Error: Provider produced inconsistent result after apply
When applying changes to honeycombio_query_annotation.nice, provider
"provider[\"[registry.terraform.io/honeycombio/honeycombio](http://registry.terraform.io/honeycombio/honeycombio)\"]"
produced an unexpected new value: .description: was null, but now
cty.StringVal("").
This is a bug in the provider, which should be reported in the
provider's own issue tracker.

- Introduced by #744