bugfix: ensure Summary is set on SDK v2 Diagnostics (#378)
SDKv2 based resources reporting errors that weren't complete
RFC7807-style errors reported something like the following:

> Error: Empty Summary: This is always a bug in the provider and should
be reported to the provider developers.

This fixes that by always ensuring that "Summary" is set.